template: |
  ## What’s Changed

  $CHANGES

  ## Special thanks to

  $CONTRIBUTORS
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧹 Chores'
    label: 'chore'
